FROM python:3.11-slim

RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/

RUN pip install --upgrade pip

RUN rm -f /etc/apt/sources.list.d/* && \
    echo "deb http://mirrors.aliyun.com/debian bookworm main contrib non-free non-free-firmware" > /etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian bookworm-updates main contrib non-free non-free-firmware" >> /etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian bookworm-backports main contrib non-free non-free-firmware" >> /etc/apt/sources.list && \
    echo "deb http://mirrors.aliyun.com/debian-security bookworm-security main contrib non-free non-free-firmware" >> /etc/apt/sources.list && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app/mcp-openapi
RUN mkdir -p /app/aworld/gaia-benchmark/fs

WORKDIR /app/mcp-openapi

COPY ./aworld aworld
COPY ./mcp_servers mcp_servers

RUN apt-get update && apt-get install -y nodejs npm

RUN pip install -r mcp_servers/requirements.txt




RUN pip install build

RUN python -m build && \
    pip install dist/mcp_openapi-0.1.9-py3-none-any.whl

CMD [ "mcp-openapi", "--config_path", "config.json", "--port", "9090" ]
